(cl:defpackage ur_msgs-msg
  (:use )
  (:export
   "<ROBOTSTATERTMSG>"
   "ROBOTSTATERTMSG"
   "<IOSTATES>"
   "IOSTATES"
   "<DIGITAL>"
   "DIGITAL"
   "<TOOLDATAMSG>"
   "TOOLDATAMSG"
   "<ROBOTMODEDATAMSG>"
   "ROBOTMODEDATAMSG"
   "<ANALOG>"
   "ANALOG"
   "<MASTERBOARDDATAMSG>"
   "MASTERBOARDDATAMSG"
  ))

