(cl:defpackage controller_manager_msgs-msg
  (:use )
  (:export
   "<HARDWAREINTERFACERESOURCES>"
   "HARDWAREINTERFACERESOURCES"
   "<CONTROLLERSTATE>"
   "CONTROLLERSTATE"
   "<CONTROLLERSSTATISTICS>"
   "CONTROLLERSSTATISTICS"
   "<CONTROLLERSTATISTICS>"
   "CONTROLLERSTATISTICS"
  ))

